### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#1]
This

**1:**

``` objc
if (....) {
  // ....
} 

else {
  // ....
}
```

vs

**2:**

``` objc
if (....) {
  // ....
} else {
  // ....
}
```

**Comment by 3lvis** [comment]
I prefer the second one because if/else if/else in my opinion should be chained. The first one looks like they can live by themselves. Also it implies that you could put things between if and else which is wrong.

**Following 1 this should be possible:**

``` objc
if (....) {
  // ....
} 

NSArray *processedItems = ....

else {
  // ....
}
```

**Comment by heumn** [comment]
You wrote #1 wrong, thus what you imply is not really possible.

```
if (....) {
  // ....
} 
else {
  // ....
}
```

BUT it is a good, and valid point that it might appear easier to get that they are chained.

**Comment by heumn** [comment]
do you do the same for if else if? That where I really like the (subjectively) clarity of having a new line

```
if (....) {
  // ....
} 
else if (....) {
  // ....
}
else {
  // ....
}
```

**Comment by 3lvis** [comment]
I would do this

``` objc
if (....) {
  // ....
} else if (....) {
  // ....
} else {
  // ....
}
```

**Comment by heumn** [comment]
This is not crucial for me at all, and from thinking about it, I think this is just old style that is stuck.
I can not reason logically for why it deserves a new line, so lets do it like you do it.

Any input @mariusfeldmann ?

**Comment by mariusfeldmann** [comment]
I'm with elvis. The last one looks good

**Comment by heumn** [comment]
Then this is settled :+1:

**Comment by 3lvis** [comment]
:tada:

**Comment by gromgull** [comment]
I am late to the party - but I agree on your conclusion (and option 1 is crazy :) )

**Comment by heumn** [comment]
@gromgull reason why this is even a discussion is my undying love for (_most_) of what these guys do:

https://github.com/NYTimes/objective-c-style-guide

**Comment by 3lvis** [comment]
[The original author](https://github.com/mattbischoff) did a great job, after he left I don't know what happened.

**Comment by heumn** [comment]
I do

![Alt Text](https://media1.giphy.com/media/pgHJTBBlrNXEs/200.gif)
