### ISSUE TITLE
Best practice on laying out subviews in UITableView/UICollectionView

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#13]

**Comment by heumn** [comment]
Interesting question. What are your concerns?

**Comment by 3lvis** [comment]
Just wanted to add something to be consistent when doing this type of UI.

**Comment by 3lvis** [comment]
We need an example that uses buttons, lazy loading and autolayout.

**Comment by 3lvis** [comment]
We now have convenience subclasses for this. https://github.com/UseSweet/SweetUIKit
