### ISSUE TITLE
iOS-team workshop

### ISSUE THREAD

**Issue by marijnschilling** [bakkenbaeck/iOS-playbook#35]
We'll be working together for four days to streamline the iOS team and make sure we're all on the same page. 

The goal is to optimise the way we work together by:
- Making guidelines on how we write code so that we can share and reuse it. 
- Building a simple app together so we cover all the points of architecture and process. (It'll be a photo app to demo our open source libraries.)
- Discussing and tackling common problems in code and process. 
#### Discussing personal points:
- [ ]  Discussing common problems in code, and tackle them either in the Unsplash app or in a separate session
- [ ] Discussing common problems in the work process so we know each others pitfalls and strengths!
- [ ] Discussing toolchain and process. How can we all benefit from better, smarter, faster tools. (Ideally, we all learn a bit about the tools some of us use that the others don't.)
#### Discussing general things in the B&B process:
- [ ] Discussing and making guidelines for how and what to contribute to the SweetUIKit (tuesday)
- [ ] Talking about the process of working together (wednesday)
- [ ] Discussing how we handle clients (thursday)
- [ ] Going over and adding things to the iOS playbook so we're all on the same page and new employees will be too (friday)
#### Create a small app to showcase our open source libraries based on the open [unsplash](https://unsplash.com/) api, where we'll pay extra attention to:
- [ ] Define (and redefine) standards in architecture
- [ ] Revisit iOS tests
- [ ] Look at how we can make away with the boilerplate from CollectionView and TableView
- [ ] Look at Autolayout + StackView
#### Have fun together!
- [ ] Go to dinner on Friday 🎉
- [ ] Make **at least** one joke p.p once a day
- [ ] Create a secret handshake for the iOS-team

**Comment by marijnschilling** [comment]
Planning for Tuesday: 
- [ ] 1h: First discuss the common code problems and see if we can tackle them in the unsplash project or need to make separate sessions for that  
- [ ] 1h: Discuss our personal difficulties and strengths, might try to come up with a “fun” way of doing this 🤔
- [ ] 45m: Discuss what tools we use, it could be good to each decide on one of our favourite tools and give a demo on it during the week.
- [ ] 45m: Make the planning of the rest of the days together, while trying to fit as many things as possible in building the Unsplash app together. (I read that working and experimenting together works better than talking/listening: [👀](https://medium.com/@swiftalps/the-concept-behind-the-swift-alps-5b07e04c7ed1#.ign9fbb9o)) 

#### Let’s use most of the day to go over SweetUIKit (4h)
- [ ] Elvis explains what he did until now and why  ¯\_(ツ)_/¯? (30m)
- [ ] Discuss what where we want to go from here (1h)
- [ ] Discuss how to incorporate more testing (30m)
- [ ] Write the actual guidelines (2h) (Divide topics, write the guidelines, get feedback, process feedback. Maybe even make new repo’s for new B&B Kit’s)

**Comment by 3lvis** [comment]
Moved to #36
