### ISSUE TITLE
Add a rule to disable merge commits to the github guidelines

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#41]
<img width="752" alt="screen shot 2016-08-02 at 11 16 38" src="https://cloud.githubusercontent.com/assets/1088217/17323472/a5d12a08-58a2-11e6-921a-75bf45e2570f.png">

**Comment by 3lvis** [comment]
This section could be _starting a new project_ where we'll mention the steps to use the app-template and so on.

**Comment by elland** [comment]
🙆 good idea.

**Comment by 3lvis** [comment]
This is quite straightforward, gonna move it to https://github.com/bakkenbaeck/iOS-playbook/pull/71

**Comment by elland** [comment]
:shipit:
