### ISSUE TITLE
Document type inference for assigned values

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#57]
``` swift
self.backgroundColor = .redColor()
```

vs

``` swift
self.backgroundColor = UIColor.redColor()
```

**Comment by elland** [comment]
`color` all the colours. 😛

**Comment by 3lvis** [comment]
💥

**Comment by 3lvis** [comment]
```swift
struct Theme {
     class var loginTint = UIColor.red
}
```

```swift
self.backgroundColor =  Theme.loginBackground
self.button.tintColor =  Theme.loginTint
```

**Comment by elland** [comment]
We should probably also reassess and address the type annotation. I want to revisit the `as Something` and go back to `let a: Something` instead. Since the first one breaks in a few of situations, but the latter never does. It's also faster to compile. 😄

**Comment by 3lvis** [comment]
Doing some spring cleaning, please open a new issue if you still want to do this.
