### ISSUE TITLE
iOS interview questions

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#58]
_(and reasoning why you would ask this)_

**Comment by marijnschilling** [comment]
- What would be an issue in the design for which you would discuss a different approach with the designer? And what would be an issue where you would just let it slide and implement it as it is. What is your view on where that boundary lies?
- What would be an issue in the back-end design for which you would discuss a different approach with the back-end designer? And what would be an issue where you would just let it slide and implement it as it is. What is your view on where that boundary lies?

Reasoning: I think it's good if we hire people that have a critical view on the design of an app and the design of a backend.

**Comment by 3lvis** [comment]
Started here https://github.com/bakkenbaeck/iOS-playbook/pull/59

**Comment by elland** [comment]
Do we have more, aside from the ones we just added there? Can we add @marijnschilling's?

**Comment by 3lvis** [comment]
I think they are very open questions, we should rephrase them to become more of a conversation starter.

**Comment by 3lvis** [comment]
> Have you faced any challenges when working with designers and/or backend developers? Could you tell us a bit more about your experience on collaborating with both?

**Comment by elland** [comment]
I like this.

**Comment by 3lvis** [comment]
Or set up some scenarios:
- If the designer asks you to implement a difficult UI or interaction that conflicts with some iOS design paradigms how you would handle communicating this with them.
- If there's some inconsistency in the backend or bug, how much would you change in the iOS app in order to avoid changes in the backend and how much you would require the backend to implement this changes for you?

I think this all is very hard to ask, it's probably to keep it very open.

**Comment by 3lvis** [comment]
Setting up scenarios is most likely going to constrain us to very close and obvious answers.

**Comment by elland** [comment]
@3lvis "with them" instead of "him/her". 👍
