### ISSUE TITLE
Switching to Realm

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#69]

**Comment by elland** [comment]
I'm for it, for now. Glad to hear con arguments. 🆗

**Comment by 3lvis** [comment]
I think it would be more about requirements on things we should be able to do.
- NSFetchedResultsController replacement (https://github.com/SyncDB/DATASource)
- Automatic JSON to database parsing (https://github.com/syncdb/sync)

**Comment by elland** [comment]
Regarding `NSFetchedResultsController`, I think it fits well with our plan of designing an almost drop-in replacement for it, that doesn't require a specific back-end, remember?

Regarding JSON: I think I agree with the Swift team, that automatic mapping is bad for your health. 🤔

**Comment by 3lvis** [comment]
@Elland I think we should find or build the necessary tooling before moving onto Realm.

Did you like it on the Pinboard client?

**Comment by 3lvis** [comment]
Automatic mapping makes a lot of sense most of the time. I see that there could be edge cases but is something you don't want to do manually.

**Comment by elland** [comment]
I think it really simplified my life by a lot, compared to CoreData, that is so full of cruft and boilerplate by comparison.

Necessary tooling: it makes more sense to implement as we go, for now. It's part of the required groundwork for the first app we build using it and then, as the second app builds on top of it, and so on. Instead of starting it off by designing something without a real use-case. What do you think?

Auto-mapping: I'd rather have a very shallow and simple `mapping definition`, could be as simple as a dictionary or an `enum` that just maps a key to a json string.

**Comment by 3lvis** [comment]
Personally before moving from Core Data I think those two things are required to be as productive as with Core Data, until then I would say we keep using Core Data.

**Comment by 3lvis** [comment]
I remember seeing some `NSFetchedResultsController` replacement somewhere. Gonna look for it later when I got some time.

**Comment by elland** [comment]
@3lvis if it's the one I started, it was for Pinboard.

**Comment by 3lvis** [comment]
No, no, another one. It was either https://github.com/Roobiq/RBQFetchedResultsController or https://github.com/redbooth/RealmResultsController.

**Comment by 3lvis** [comment]
I would need to take a proper look at them before remembering.

**Comment by 3lvis** [comment]
I think I could build a Realm Sync clone using the structure in the Realm file. I need to take a closer look at that as well.

https://realm.io/docs/swift/latest/#realm-browser

**Comment by elland** [comment]
That sounds like a terrible idea. We should build it on top of their notification system, like one of the examples you mentioned there.

The other one: 

> In order for the RealmResultsController to receive the change events in a Realm, you must use our custom methods. Those are declared in a Realm Extension and are wrappers for the original Realm methods

I'll gladly pass on that one.

**Comment by elland** [comment]
I also find it hard to believe we need a controller with 2k LOC for this. 🤔

**Comment by 3lvis** [comment]
I'll get back to you when I look closer into this. I think moving to Realm might be a good idea, but I need to make sure that we have what we need before doing so.

**Comment by 3lvis** [comment]
@Elland we don't have to use what's out there if it doesn't fit our needs, we could use it as inspiration, though.

**Comment by elland** [comment]
@3lvis sounds good to me. 🙆

**Comment by elland** [comment]
@marijnschilling should have some say as well.

**Comment by marijnschilling** [comment]
I have no idea what Realm is! 🙈 Will look into it tomorrow! I'll get back to you guys about this.
Though I'm usually up for giving things a try!

**Comment by 3lvis** [comment]
I think this is settled. The best way to improve our tooling is to face the problems first hand. I'll close this and keep it as a todo in the GETTING_STARTED document.
