### ISSUE TITLE
k prefix for constants that aren't related to enum

### ISSUE THREAD

**Issue by heumn** [bakkenbaeck/iOS-playbook#7]
So

static kBBStringName \* const = @"name"

not 

static BBStringName \* const = @"name"

**Comment by 3lvis** [comment]
Any reason on why you would prefer this?

**Comment by 3lvis** [comment]
Apple Guidelines:

[Constants in Cocoa (Objective-C)](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingIvarsAndTypes.html#//apple_ref/doc/uid/20001284-BAJGIIJE):

``` objc
const float NSLightGray;
```

[Constants in Core Foundation (C)](https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFDesignConcepts/Articles/NamingConventions.html#//apple_ref/doc/uid/20001110-CJBEJBHH):

> A major programming-interface convention in Core Foundation is to use the name of the opaque type that is most closely related to a symbol as the symbol’s prefix. For functions, this prefix identifies not only the type to which the function “belongs” but usually the type of object that is the target of the function’s action. (An exception to this convention are constants, which put “k” before the type prefix.) Here are a few examples from the header files:

``` c
/* from CFDictionary.h */
CF_EXPORT CFIndex CFDictionaryGetCountOfKey(CFDictionaryRef dict, const void *key);
/* from CFString.h */
typedef UInt32 CFStringEncoding;
/* from CFCharacterSet.h */
typedef enum {
    kCFCharacterSetControl = 1,
    kCFCharacterSetWhitespace,
    kCFCharacterSetWhitespaceAndNewline,
    kCFCharacterSetDecimalDigit,
    kCFCharacterSetLetter,
    kCFCharacterSetLowercaseLetter,
    kCFCharacterSetUppercaseLetter,
    kCFCharacterSetNonBase,
    kCFCharacterSetDecomposable,
    kCFCharacterSetAlphaNumeric,
    kCFCharacterSetPunctuation,
    kCFCharacterSetIllegal
} CFCharacterSetPredefinedSet;
```

**Comment by 3lvis** [comment]
I think it's safe if we keep dropping the `k` for constants since it seems like a common guideline between what Apple does and us, at least for Objective-C.

**Comment by heumn** [comment]
Just personal taste and what I have been doing. I have gotten used to differentiate enums from constants like this. But that might just as well be that I should learn to name the two better. 

This is settled for me. We should leave it like we do it no, without the extra "k". Thanks for your input!
