### ISSUE TITLE
Document defaulting new project to Carthage

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#70]
And checking-in the dependencies folder.

**Comment by elland** [comment]
🙆 👌

**Comment by elland** [comment]
We need to update our template project?

**Comment by 3lvis** [comment]
@Elland Already updated. Removed all the CocoaPods stuff. 

https://github.com/bakkenbaeck/app-template

**Comment by 3lvis** [comment]
Will move to https://github.com/bakkenbaeck/iOS-playbook/pull/71

**Comment by elland** [comment]
🆗
