### ISSUE TITLE
Reconsider type annotations because of generic methods and compilation times

### ISSUE THREAD

**Issue by elland** [bakkenbaeck/iOS-playbook#79]

**Comment by 3lvis** [comment]
We should check for slowly compiled methods before doing something about them.
http://khanlou.com/2016/12/guarding-against-long-compiles

**Comment by 3lvis** [comment]
Basically, you mean:

```swift
let percentage: Double = 10
```

Instead of:

```swift
let percentage = Double(10)
```

**Comment by elland** [comment]
👍 

also not:
```swift
let percetange = 10 as Double
````

**Comment by 3lvis** [comment]
We don't do that one, though.

**Comment by elland** [comment]
Not for this specific case. 🤔

Thinking about stuff like `let json = json as? [String: Any]` and there I think we should keep the `as` stuff for sure. No better way.

**Comment by elland** [comment]
So yeah, nevermind the `as Double`.

**Comment by 3lvis** [comment]
What about:

```swift
let collectionView = UICollectionView()
```

Should it be:

```swift
let collectionView: UICollectionView = UICollectionView()
```

Or are you thinking in doing this for some specific cases?

**Comment by elland** [comment]
Only where type can't be correctly inferred. _Code should be as verbose as needed but not verboser*_

_* not a real word_

**Comment by 3lvis** [comment]
>Only where type can't be correctly inferred.

```swift
let percentage = Double(10)
```

What's incorrect about this?

**Comment by elland** [comment]
Nothing, it's just become inconsistent with the rest as we adopt type annotation instead. 👍

**Comment by 3lvis** [comment]
So we have two options:

Option A:

Use type annotation when it's needed.
```swift
let percentage = Double(10)
let collectionView = UICollectionView()
lazy var view: UIView = {

}()

// Type annotation required here, it's obvious, if you don't add it won't work.
let generic: Generic = Generic(value: 1) * Generic(value: 2)
```

Option B:

Always use type annotation unless the type is obvious such as when assigning a new instance to a variable.
```swift
let percentage: Double = 10

// Type annotation is not needed here, since it's obvious looking at the result of UICollectionView()
let collectionView = UICollectionView() // Otherwise it would be let collectionView: UICollectionView = UICollectionView() 
lazy var view: UIView = {

}()
let generic: Generic = Generic(value: 1) * Generic(value: 2)
```

They both are pretty much the same, so I guess it all comes down to.

```swift
let percentage = Double(10)
let collectionView = UICollectionView()
```

vs 

```swift
let percentage: Double = 10
let collectionView = UICollectionView()
```

**Comment by 3lvis** [comment]
I think having the first one. "Use type annotation when it's needed." Makes more sense since it's easier to be more consistent, basically the only place where the rule will be violated will be when using generics, which is not that often.

Meanwhile. going for "Always use type annotation unless the type is obvious such as when assigning a new instance to a variable." means that you're violating the rule every time you do:

```swift 
let collectionView = UICollectionView()
```

Which is several times in any app.

**Comment by elland** [comment]
I don't think I understood your point. The rule change would mean that instead of 

```swift
let percentage = Double(10)
```

You'd do 

```swift
let percentage: Double = 10
```

So it's consistent with generics, etc. 🤔What am I missing? I don't think anything else changes.

**Comment by 3lvis** [comment]
The rule change it's only consistent with generics, which we don't use that often, not with:

```swift
let collectionView = UICollectionView()
```

Which is all over the place.

**Comment by elland** [comment]
But this doesn't change. It's still the same. 🤔

**Comment by designatednerd** [comment]
@Elland I think this has improved sufficiently in Swift 4 that we don't need this as an official standard. Do you mind if I close this out?

**Comment by elland** [comment]
@designatednerd do we have numbers on that? 👍

**Comment by designatednerd** [comment]
Not officially, but we've got the toshi project set up to warn us if anything takes more than 200ms to compile. Even on my cranky old computer the number of things we've needed to add annotations to in order to help the compiler get its shit together was far outpaced by the number of things which just needed to be simplified.

**Comment by elland** [comment]
worth a try 👍
