### ISSUE TITLE
Declare constants in headers as extern variables

### ISSUE THREAD

**Issue by heumn** [bakkenbaeck/iOS-playbook#8]
Declare constants in headers as extern variables which are defined in the corresponding implementation file.

extern NSString \* const  kCHRDeclerativeNameOfString;

Constants should be declared like this if they are available across files. And how do you make it available? Like we do with everything else. We create a decleration in the header file, and we define it in the implementation file. 

http://ashfurrow.com/blog/structuring-modern-objective-c/

**Comment by 3lvis** [comment]
I think this makes sense, exposing the values attached to a constant isn't a requirement and just doing: 

``` objc
extern NSString * const BBDefaultsLastSystemUptimeDateKey;
```

Instead of:

``` objc
static NSString * const BBDefaultsLastSystemUptimeDateKey = @"BBDefaultsLastSystemUptimeDateKey";
```

Leads to a cleaner API.

**Comment by heumn** [comment]
Great :)

**Comment by 3lvis** [comment]
Ideally the issue should be closed once the PR gets merged.

**Comment by heumn** [comment]
Ok :)
