### ISSUE TITLE
Document why external testers vs internal testers on TestFlight

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#84]
- Internal requires that the user is an iTunes Connect member, so they can't reuse the same email for different accounts.
- Internal sends emails about every little issue regarding your builds, you don't want this for your testers.
- Releasing to external testers takes the same time as doing it for internal testers if you only increment the build number

**Comment by zimumba** [comment]
> Internal requires that the user is an iTunes Connect member, so they can't reuse the same email for different accounts.
--
i thought it's an idea of why do we use TF at all. I mean to keep all the builds in the same place. We could just use BuddyBuild delivering system otherwise. What are the benefits of TF in this case?

> Internal sends emails about every little issue regarding your builds, you don't want this for your testers.
--
Do you mean f . e. some issue during build uploading?

> Releasing to external testers takes the same time as doing it for internal testers if you only increment the build number
--
got it

**Comment by 3lvis** [comment]
>i thought it's an idea of why do we use TF at all. I mean to keep all the builds in the same place. We could just use BuddyBuild delivering system otherwise. What are the benefits of TF in this case?

Maybe you didn't understand my point. I meant if I'm registered as an internal user of Company A, then when I try to use the same mail to register with my own Company B, it won't work. I have to use a different email. With external testing, you can use the same email for both Company A and Company B.

**Comment by 3lvis** [comment]
>Internal sends emails about every little issue regarding your builds, you don't want this for your testers.

Also when your build finishes processing, when it gets released, I mean for pretty much anything. Your testers should only get emails when the build is ready for testing.

**Comment by 3lvis** [comment]
Doing some spring cleaning, please open a new issue if you still want to do this.
