### ISSUE TITLE
Discourage usage of #imageLiteral and #colorLiteral

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#91]
Why? For images there's no easy way to see which file name they are pointing to, so if you want to search and replace, nope, not happening. For colors is similar, if you want to check if you're using the same color somewhere else you can't there's only a block of color and you can't see the contents of it.

<img width="1464" alt="screen shot 2017-01-19 at 16 55 17" src="https://cloud.githubusercontent.com/assets/1088217/22113905/17520c88-de68-11e6-8b7c-77f0a0079533.png">

**Comment by onmyway133** [comment]
@3lvis can I comment here? 😬  I think we can just use https://github.com/mac-cain13/R.swift which offers type safety and code completion

**Comment by elland** [comment]
@onmyway133 can't see why not. 🙆🏼‍♂️💪🏼

We looked into `R.swift` before but I wasn't super thrilled. Will take a closer look. 👍

**Comment by 3lvis** [comment]
Doing some spring cleaning, please open a new issue if you still want to do this.
