### ISSUE TITLE
Master Detail class name convention

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/iOS-playbook#97]
For a Recipes app right now we are using **RecipesController** and **RecipeController**, even though this does the job, I think it would be better if we have a keyword that can extend between multiple projects to name this classes. I'm proposing that we use: **RecipeListController** and **RecipeDetailController**.

What do you think?

**Comment by kostiakoval** [comment]
Hi, can I add my comments here? 👍 for the renaming, I agree that the `s` letter is not enough to differentiate the components.   
Another solution could be `RecipesController` and `RecipeDetailController`

**Comment by elland** [comment]
@3lvis Not really that fond of calling things `lists`. 

@kostiakoval I like that. Simple and just as verbose as we need to, without having to identify it visually as a list, collection, grid, etc.

**Comment by marijnschilling** [comment]
Yes I agree, I think `RecipesController` and `RecipeDetailController` will do the trick

**Comment by 3lvis** [comment]
![tumblr_lgedv2vtt21qf4x93o1_40020110725-22047-38imqt](https://cloud.githubusercontent.com/assets/1088217/23579915/e3bb96e8-00f7-11e7-9795-b8b2fa5c2718.jpg)

**Comment by 3lvis** [comment]
@Elland reasoning against using `RecipeListController`?

**Comment by elland** [comment]
@3lvis it's on my very first comment. 🤔

**Comment by marijnschilling** [comment]
I think List is confubsing, because it can either be a list or a collection of items. I think just using a plural is more accurate in this case.

**Comment by elland** [comment]
Yeah, keeping how the UI is presented out of the controller name sounds good to me. No need to rename if the presentation changes etc.

**Comment by 3lvis** [comment]
@Elland I was asking for extra clarification, "I'm not very fond" didn't seem like a proper argument. @marijnschilling's answer was great, though. I think it clarifies what you meant.

**Comment by elland** [comment]
@3lvis your answer feels like you didn't read my whole comment.

> Simple and just as verbose as we need to, without having to identify it visually as a list, collection, grid, etc.

**Comment by 3lvis** [comment]
Doing some spring cleaning, please make a new issue if you still want to do this.
